version: '3'
services:
  #Nginx Service
  webapp:
    image: nginx:alpine
    container_name: webapp
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./web-build:/usr/share/nginx/html/
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
