# => Build container
FROM nhie/builder as builder
WORKDIR /app
COPY . .
RUN yarn
RUN yarn web:build:prod

# => Run container
FROM nginx:1.18.0-alpine

# Nginx config
RUN rm -rf /etc/nginx/conf.d
COPY --from=builder /app/nginx /etc/nginx

# Static build
COPY --from=builder /app/web-build /usr/share/nginx/html/

# Copy shell scripts to container
WORKDIR /scripts
COPY --from=builder /app/scripts .

# Make our shell script executable
RUN chmod +x *.sh
