version: '3'
services:
  #Nginx Service
  webapp:
    container_name: webapp
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    build:
      context: .
      args:
        env: prod
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
